#ifndef __TRACE_H__ 
#define __TRACE_H__

// IoctlFirstDriverTraceGuid GUID provider: {86FB450A-DB03-44C6-863E-C4FB9E6741A8}
#define WPP_CONTROL_GUIDS \
    WPP_DEFINE_CONTROL_GUID( \
        IoctlFirstDriverTraceGuid, (86FB450A,DB03,44C6,863E,C4FB9E6741A8),  \
            WPP_DEFINE_BIT(TRACE_FLAG_IOCTL_FIRST_DRIVER)        /* bit  0 = 0x00000001 */ \
    )

#define WPP_LEVEL_FLAGS_LOGGER(level, flags) WPP_LEVEL_LOGGER(flags)
#define WPP_LEVEL_FLAGS_ENABLED(level, flags) (WPP_LEVEL_ENABLED(flags) && WPP_CONTROL(WPP_BIT_ ## flags).Level >= level)

// begin_wpp config
//
// FUNC IoctlFirstDriverLogTrace{LEVEL=TRACE_LEVEL_VERBOSE, FLAGS=TRACE_FLAG_IOCTL_FIRST_DRIVER} (MSG, ...);
// FUNC IoctlFirstDriverLogInfo{LEVEL=TRACE_LEVEL_INFORMATION, FLAGS=TRACE_FLAG_IOCTL_FIRST_DRIVER}(MSG, ...);
// FUNC IoctlFirstDriverLogWarning{LEVEL=TRACE_LEVEL_WARNING, FLAGS=TRACE_FLAG_IOCTL_FIRST_DRIVER}(MSG, ...);
// FUNC IoctlFirstDriverLogError{LEVEL=TRACE_LEVEL_ERROR, FLAGS=TRACE_FLAG_IOCTL_FIRST_DRIVER}(MSG, ...);
// FUNC IoctlFirstDriverLogCritical{LEVEL=TRACE_LEVEL_CRITICAL, FLAGS=TRACE_FLAG_IOCTL_FIRST_DRIVER}(MSG, ...);
//
// end_wpp
//

#endif //__TRACE_H__